/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MenuItem {
  'id' : string,
  'name' : string,
  'description' : string,
  'restaurantId' : string,
  'category' : string,
  'price' : number,
}
export interface Restaurant {
  'id' : string,
  'priceLevel' : bigint,
  'name' : string,
  'cuisineTags' : Array<string>,
  'description' : string,
  'imageUrl' : string,
  'bannerUrl' : string,
  'rating' : number,
}
export interface _SERVICE {
  '_init' : ActorMethod<[], undefined>,
  'getAllRestaurants' : ActorMethod<[], Array<Restaurant>>,
  'getMenuItemsByRestaurantId' : ActorMethod<[string], Array<MenuItem>>,
  'getRestaurantById' : ActorMethod<[string], [] | [Restaurant]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];