/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Restaurant = IDL.Record({
  'id' : IDL.Text,
  'priceLevel' : IDL.Nat,
  'name' : IDL.Text,
  'cuisineTags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'bannerUrl' : IDL.Text,
  'rating' : IDL.Float64,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'restaurantId' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_init' : IDL.Func([], [], []),
  'getAllRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
  'getMenuItemsByRestaurantId' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getRestaurantById' : IDL.Func([IDL.Text], [IDL.Opt(Restaurant)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Restaurant = IDL.Record({
    'id' : IDL.Text,
    'priceLevel' : IDL.Nat,
    'name' : IDL.Text,
    'cuisineTags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'bannerUrl' : IDL.Text,
    'rating' : IDL.Float64,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'restaurantId' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  
  return IDL.Service({
    '_init' : IDL.Func([], [], []),
    'getAllRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
    'getMenuItemsByRestaurantId' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getRestaurantById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Restaurant)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };